# Generated by Django 3.2.18 on 2023-02-20 04:54

import django.contrib.postgres.fields
from django.db import migrations, models
import tbi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tbi.models.IndexableCharField(max_length=254)),
                ('description', tbi.models.IndexableCharField(max_length=254)),
                ('author', tbi.models.IndexableCharField(max_length=254)),
                ('earliest_date', tbi.models.IndexableCharField(max_length=254)),
                ('long_description', models.TextField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=254), size=None)),
                ('historical_references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('found_in', tbi.models.IndexableCharField(max_length=254)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('recordings', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('broadsides', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('cross_references', django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=254), size=None)),
                ('same_tune', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('alternate_titles', django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=254), size=None)),
                ('notes', models.TextField()),
                ('file', tbi.models.IndexableCharField(max_length=254)),
            ],
        ),
    ]
