# Generated by Django 3.2.18 on 2023-02-20 05:31

import django.contrib.postgres.fields
from django.db import migrations, models
import tbi.models


class Migration(migrations.Migration):

    replaces = [('tbi', '0002_alter_ballad_historical_references'), ('tbi', '0003_alter_ballad_references'), ('tbi', '0004_alter_ballad_recordings'), ('tbi', '0005_alter_ballad_broadsides'), ('tbi', '0006_alter_ballad_cross_references'), ('tbi', '0007_alter_ballad_same_tune'), ('tbi', '0008_alter_ballad_alternate_titles'), ('tbi', '0009_auto_20230220_0509'), ('tbi', '0010_balladindex'), ('tbi', '0011_balladname'), ('tbi', '0012_auto_20230220_0520'), ('tbi', '0013_supptradfile'), ('tbi', '0014_alter_ballad_keywords'), ('tbi', '0015_alter_ballad_author')]

    dependencies = [
        ('tbi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballad',
            name='historical_references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='recordings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='broadsides',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='cross_references',
            field=django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=254), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='same_tune',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='alternate_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=254), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='alternate_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='author',
            field=tbi.models.IndexableCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='cross_references',
            field=django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='description',
            field=tbi.models.IndexableCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='earliest_date',
            field=tbi.models.IndexableCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='file',
            field=tbi.models.IndexableCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='found_in',
            field=tbi.models.IndexableCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='name',
            field=tbi.models.IndexableCharField(max_length=255),
        ),
        migrations.CreateModel(
            name='BalladIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tbi.models.IndexableCharField(max_length=255)),
                ('index', django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='BalladName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tbi.models.IndexableCharField(max_length=255)),
                ('title', tbi.models.IndexableCharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SuppTradFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tbi.models.IndexableCharField(max_length=255)),
                ('text', models.TextField()),
                ('file', tbi.models.IndexableCharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ballad',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=tbi.models.IndexableCharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ballad',
            name='author',
            field=tbi.models.IndexableCharField(max_length=300),
        ),
    ]
