application: folkloristorg
version: bs
runtime: python27
api_version: 1
threadsafe: false

builtins:
- appstats: on
- remote_api: on

error_handlers:
- error_code: over_quota
  file: errors/quota.html

handlers:
- url: /static
  static_dir: static

- url: /([^/]+\.(?:html|ico|txt|xml))
  upload: static/top/([^/]+\.(?:html|ico|txt|xml))
  static_files: static/top/\1

- url: /queue/.*
  script: queue.py
  login: admin

- url: .*
  script: main.py

libraries:
- name: django
  version: '1.2'
